# Generated by Django 6.0.3 on 2026-04-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slams', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slam',
            new_name='slams_slam_author__65fd3f_idx',
            old_name='slams_slam_author__8e29b5_idx',
        ),
        migrations.RenameIndex(
            model_name='slam',
            new_name='slams_slam_status_8612ee_idx',
            old_name='slams_slam_status__7e6c2c_idx',
        ),
        migrations.RenameIndex(
            model_name='slam',
            new_name='slams_slam_submitt_a6d2c1_idx',
            old_name='slams_slam_submitt_eb6775_idx',
        ),
    ]
